name: ws_controller_of_rtc
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
dependencies:
  web_socket_client_rtc_test:
    git:
      url: https://github.com/ravshanbk/web_socket_client_rtc_test.git
      ref: main





dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
